### ISSUE TITLE
Any plan for a new release for the Symfony ~3.0 support?

### ISSUE THREAD

**Issue by Lance0312** [stackphp/builder#21]
Since there is support for Symfony ~3.0 on master branch, is there any plan for rolling out new release for that?

**Comment by jsor** [comment]
I'd also appreciate a new release with Symfony 3 support.

**Comment by jibran** [comment]
[dev-master](https://github.com/stackphp/builder/blob/master/composer.json#L14-L15) already supports Symfony 3. Can we have a new tag release?

**Comment by jibran** [comment]
Drupal 8 issue https://www.drupal.org/node/2712637 is postponed on the release of the official tag.

**Comment by simensen** [comment]
I'll try to work on this tonight.

**Comment by jibran** [comment]
Any update here?

**Comment by polybuildr** [comment]
+1, would love to have this. Simply cannot install as of now due to requirement conflicts.

**Comment by jibran** [comment]
@simensen hi! it's been more then a month and Drupal 8 is almost ready for Symfony 3. Can we have an update on this? Is there anyway we can help this process to move forward quickly? Thanks for looking into it.

**Comment by simensen** [comment]
I've finally tagged this. I apologize for the delay. Let me know if anyone runs into any problems. Thanks for your patience!

**Comment by dawehner** [comment]
Nice, thanks a lot!
